/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateAdminRequest = IDL.Record({
  'institute_code' : IDL.Text,
  'institute_name' : IDL.Text,
  'address' : IDL.Opt(IDL.Text),
});
export const UserId = IDL.Text;
export const Timestamp = IDL.Int;
export const Admin = IDL.Record({
  'id' : UserId,
  'created_at' : Timestamp,
  'institute_code' : IDL.Text,
  'institute_name' : IDL.Text,
  'address' : IDL.Opt(IDL.Text),
  'profile_id' : UserId,
});
export const NotificationType = IDL.Variant({
  'custom' : IDL.Null,
  'fee_due' : IDL.Null,
  'overdue' : IDL.Null,
  'payment_received' : IDL.Null,
});
export const CreateNotificationRequest = IDL.Record({
  'title' : IDL.Text,
  'type' : NotificationType,
  'student_id' : IDL.Opt(UserId),
  'message' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'is_read' : IDL.Bool,
  'title' : IDL.Text,
  'admin_id' : UserId,
  'type' : NotificationType,
  'student_id' : IDL.Opt(UserId),
  'created_at' : Timestamp,
  'message' : IDL.Text,
});
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'student' : IDL.Null });
export const CreateProfileRequest = IDL.Record({
  'avatar_url' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : Role,
  'email' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
});
export const Profile = IDL.Record({
  'id' : UserId,
  'updated_at' : Timestamp,
  'avatar_url' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : Role,
  'created_at' : Timestamp,
  'email' : IDL.Text,
  'is_active' : IDL.Bool,
  'phone' : IDL.Opt(IDL.Text),
});
export const CreateStudentRequest = IDL.Record({
  'joined_date' : Timestamp,
  'class' : IDL.Text,
  'name' : IDL.Text,
  'fee_start_date' : Timestamp,
  'email' : IDL.Text,
  'monthly_fee' : IDL.Nat,
  'course' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : IDL.Text,
  'updated_at' : Timestamp,
  'joined_date' : Timestamp,
  'admin_id' : UserId,
  'class' : IDL.Text,
  'name' : IDL.Text,
  'fee_start_date' : Timestamp,
  'created_at' : Timestamp,
  'email' : IDL.Text,
  'is_active' : IDL.Bool,
  'monthly_fee' : IDL.Nat,
  'course' : IDL.Text,
  'profile_id' : IDL.Opt(UserId),
});
export const PaymentMethod = IDL.Variant({
  'card' : IDL.Null,
  'cash' : IDL.Null,
  'cheque' : IDL.Null,
  'online' : IDL.Null,
});
export const MonthlyPayment = IDL.Record({
  'id' : IDL.Text,
  'month' : IDL.Text,
  'payment_date' : Timestamp,
  'admin_id' : UserId,
  'student_id' : IDL.Text,
  'created_at' : Timestamp,
  'payment_method' : PaymentMethod,
  'amount_paid' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
});
export const RecordPaymentRequest = IDL.Record({
  'month' : IDL.Text,
  'payment_date' : Timestamp,
  'student_id' : IDL.Text,
  'payment_method' : PaymentMethod,
  'amount_paid' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
});
export const UpdatePaymentRequest = IDL.Record({
  'payment_date' : IDL.Opt(Timestamp),
  'payment_method' : IDL.Opt(PaymentMethod),
  'amount_paid' : IDL.Opt(IDL.Nat),
  'notes' : IDL.Opt(IDL.Text),
});
export const UpdateProfileRequest = IDL.Record({
  'avatar_url' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'is_active' : IDL.Opt(IDL.Bool),
  'phone' : IDL.Opt(IDL.Text),
});
export const UpdateStudentRequest = IDL.Record({
  'class' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'is_active' : IDL.Opt(IDL.Bool),
  'monthly_fee' : IDL.Opt(IDL.Nat),
  'course' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAdmin' : IDL.Func([CreateAdminRequest], [Admin], []),
  'createNotification' : IDL.Func(
      [CreateNotificationRequest],
      [Notification],
      [],
    ),
  'createProfile' : IDL.Func([CreateProfileRequest], [Profile], []),
  'createStudent' : IDL.Func([CreateStudentRequest], [Student], []),
  'deletePayment' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAdminByProfile' : IDL.Func([], [IDL.Opt(Admin)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getNotificationsByAdmin' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getNotificationsByStudent' : IDL.Func(
      [],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getPaymentsByAdmin' : IDL.Func([], [IDL.Vec(MonthlyPayment)], ['query']),
  'getPaymentsByStudent' : IDL.Func([], [IDL.Vec(MonthlyPayment)], ['query']),
  'getStudentByProfile' : IDL.Func([], [IDL.Opt(Student)], ['query']),
  'getStudentsByAdmin' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [IDL.Nat], []),
  'markNotificationRead' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'recordPayment' : IDL.Func([RecordPaymentRequest], [MonthlyPayment], []),
  'updatePayment' : IDL.Func(
      [IDL.Text, UpdatePaymentRequest],
      [IDL.Opt(MonthlyPayment)],
      [],
    ),
  'updateProfile' : IDL.Func([UpdateProfileRequest], [IDL.Opt(Profile)], []),
  'updateStudent' : IDL.Func(
      [IDL.Text, UpdateStudentRequest],
      [IDL.Opt(Student)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateAdminRequest = IDL.Record({
    'institute_code' : IDL.Text,
    'institute_name' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
  });
  const UserId = IDL.Text;
  const Timestamp = IDL.Int;
  const Admin = IDL.Record({
    'id' : UserId,
    'created_at' : Timestamp,
    'institute_code' : IDL.Text,
    'institute_name' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
    'profile_id' : UserId,
  });
  const NotificationType = IDL.Variant({
    'custom' : IDL.Null,
    'fee_due' : IDL.Null,
    'overdue' : IDL.Null,
    'payment_received' : IDL.Null,
  });
  const CreateNotificationRequest = IDL.Record({
    'title' : IDL.Text,
    'type' : NotificationType,
    'student_id' : IDL.Opt(UserId),
    'message' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'is_read' : IDL.Bool,
    'title' : IDL.Text,
    'admin_id' : UserId,
    'type' : NotificationType,
    'student_id' : IDL.Opt(UserId),
    'created_at' : Timestamp,
    'message' : IDL.Text,
  });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'student' : IDL.Null });
  const CreateProfileRequest = IDL.Record({
    'avatar_url' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : Role,
    'email' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
  });
  const Profile = IDL.Record({
    'id' : UserId,
    'updated_at' : Timestamp,
    'avatar_url' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : Role,
    'created_at' : Timestamp,
    'email' : IDL.Text,
    'is_active' : IDL.Bool,
    'phone' : IDL.Opt(IDL.Text),
  });
  const CreateStudentRequest = IDL.Record({
    'joined_date' : Timestamp,
    'class' : IDL.Text,
    'name' : IDL.Text,
    'fee_start_date' : Timestamp,
    'email' : IDL.Text,
    'monthly_fee' : IDL.Nat,
    'course' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : IDL.Text,
    'updated_at' : Timestamp,
    'joined_date' : Timestamp,
    'admin_id' : UserId,
    'class' : IDL.Text,
    'name' : IDL.Text,
    'fee_start_date' : Timestamp,
    'created_at' : Timestamp,
    'email' : IDL.Text,
    'is_active' : IDL.Bool,
    'monthly_fee' : IDL.Nat,
    'course' : IDL.Text,
    'profile_id' : IDL.Opt(UserId),
  });
  const PaymentMethod = IDL.Variant({
    'card' : IDL.Null,
    'cash' : IDL.Null,
    'cheque' : IDL.Null,
    'online' : IDL.Null,
  });
  const MonthlyPayment = IDL.Record({
    'id' : IDL.Text,
    'month' : IDL.Text,
    'payment_date' : Timestamp,
    'admin_id' : UserId,
    'student_id' : IDL.Text,
    'created_at' : Timestamp,
    'payment_method' : PaymentMethod,
    'amount_paid' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
  });
  const RecordPaymentRequest = IDL.Record({
    'month' : IDL.Text,
    'payment_date' : Timestamp,
    'student_id' : IDL.Text,
    'payment_method' : PaymentMethod,
    'amount_paid' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
  });
  const UpdatePaymentRequest = IDL.Record({
    'payment_date' : IDL.Opt(Timestamp),
    'payment_method' : IDL.Opt(PaymentMethod),
    'amount_paid' : IDL.Opt(IDL.Nat),
    'notes' : IDL.Opt(IDL.Text),
  });
  const UpdateProfileRequest = IDL.Record({
    'avatar_url' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'is_active' : IDL.Opt(IDL.Bool),
    'phone' : IDL.Opt(IDL.Text),
  });
  const UpdateStudentRequest = IDL.Record({
    'class' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'is_active' : IDL.Opt(IDL.Bool),
    'monthly_fee' : IDL.Opt(IDL.Nat),
    'course' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAdmin' : IDL.Func([CreateAdminRequest], [Admin], []),
    'createNotification' : IDL.Func(
        [CreateNotificationRequest],
        [Notification],
        [],
      ),
    'createProfile' : IDL.Func([CreateProfileRequest], [Profile], []),
    'createStudent' : IDL.Func([CreateStudentRequest], [Student], []),
    'deletePayment' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAdminByProfile' : IDL.Func([], [IDL.Opt(Admin)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getNotificationsByAdmin' : IDL.Func(
        [],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getNotificationsByStudent' : IDL.Func(
        [],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getPaymentsByAdmin' : IDL.Func([], [IDL.Vec(MonthlyPayment)], ['query']),
    'getPaymentsByStudent' : IDL.Func([], [IDL.Vec(MonthlyPayment)], ['query']),
    'getStudentByProfile' : IDL.Func([], [IDL.Opt(Student)], ['query']),
    'getStudentsByAdmin' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [IDL.Nat], []),
    'markNotificationRead' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'recordPayment' : IDL.Func([RecordPaymentRequest], [MonthlyPayment], []),
    'updatePayment' : IDL.Func(
        [IDL.Text, UpdatePaymentRequest],
        [IDL.Opt(MonthlyPayment)],
        [],
      ),
    'updateProfile' : IDL.Func([UpdateProfileRequest], [IDL.Opt(Profile)], []),
    'updateStudent' : IDL.Func(
        [IDL.Text, UpdateStudentRequest],
        [IDL.Opt(Student)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };