/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Admin {
  'id' : UserId,
  'created_at' : Timestamp,
  'institute_code' : string,
  'institute_name' : string,
  'address' : [] | [string],
  'profile_id' : UserId,
}
export interface ClassRecord {
  'id' : string,
  'admin_id' : UserId,
  'name' : string,
  'description' : string,
  'created_at' : Timestamp,
}
export interface CreateAdminRequest {
  'institute_code' : string,
  'institute_name' : string,
  'address' : [] | [string],
}
export interface CreateClassForm { 'name' : string, 'description' : string }
export interface CreateNotificationRequest {
  'title' : string,
  'type' : NotificationType,
  'student_id' : [] | [UserId],
  'message' : string,
}
export interface CreateProfileRequest {
  'avatar_url' : [] | [string],
  'name' : string,
  'role' : Role,
  'email' : string,
  'phone' : [] | [string],
}
export interface CreateSectionForm { 'name' : string, 'class_id' : string }
export interface CreateStudentRequest {
  'dob' : [] | [string],
  'joined_date' : Timestamp,
  'class' : string,
  'name' : string,
  'fee_start_date' : Timestamp,
  'section' : [] | [string],
  'admission_date' : [] | [string],
  'email' : string,
  'enrollment_number' : [] | [string],
  'parent_phone' : [] | [string],
  'address' : [] | [string],
  'gender' : [] | [string],
  'phone' : [] | [string],
  'monthly_fee' : bigint,
  'course' : string,
  'parent_name' : [] | [string],
}
export interface MonthlyPayment {
  'id' : string,
  'month' : string,
  'payment_date' : Timestamp,
  'admin_id' : UserId,
  'student_id' : string,
  'created_at' : Timestamp,
  'payment_method' : PaymentMethod,
  'amount_paid' : bigint,
  'notes' : [] | [string],
}
export interface Notification {
  'id' : string,
  'is_read' : boolean,
  'title' : string,
  'admin_id' : UserId,
  'type' : NotificationType,
  'student_id' : [] | [UserId],
  'created_at' : Timestamp,
  'message' : string,
}
export type NotificationType = { 'custom' : null } |
  { 'fee_due' : null } |
  { 'overdue' : null } |
  { 'payment_received' : null };
export type PaymentMethod = { 'card' : null } |
  { 'cash' : null } |
  { 'cheque' : null } |
  { 'online' : null };
export interface Profile {
  'id' : UserId,
  'updated_at' : Timestamp,
  'avatar_url' : [] | [string],
  'name' : string,
  'role' : Role,
  'created_at' : Timestamp,
  'email' : string,
  'is_active' : boolean,
  'phone' : [] | [string],
}
export interface RecordPaymentRequest {
  'month' : string,
  'payment_date' : Timestamp,
  'student_id' : string,
  'payment_method' : PaymentMethod,
  'amount_paid' : bigint,
  'notes' : [] | [string],
}
export type Role = { 'admin' : null } |
  { 'student' : null };
export interface SectionRecord {
  'id' : string,
  'admin_id' : UserId,
  'name' : string,
  'created_at' : Timestamp,
  'class_id' : string,
}
export interface Student {
  'id' : string,
  'dob' : [] | [string],
  'updated_at' : Timestamp,
  'joined_date' : Timestamp,
  'admin_id' : UserId,
  'class' : string,
  'name' : string,
  'fee_start_date' : Timestamp,
  'section' : [] | [string],
  'created_at' : Timestamp,
  'admission_date' : [] | [string],
  'email' : string,
  'enrollment_number' : [] | [string],
  'parent_phone' : [] | [string],
  'address' : [] | [string],
  'gender' : [] | [string],
  'is_active' : boolean,
  'phone' : [] | [string],
  'monthly_fee' : bigint,
  'course' : string,
  'profile_id' : [] | [UserId],
  'parent_name' : [] | [string],
}
export type Timestamp = bigint;
export interface UpdateClassForm { 'name' : string, 'description' : string }
export interface UpdatePaymentRequest {
  'payment_date' : [] | [Timestamp],
  'payment_method' : [] | [PaymentMethod],
  'amount_paid' : [] | [bigint],
  'notes' : [] | [string],
}
export interface UpdateProfileRequest {
  'avatar_url' : [] | [string],
  'name' : [] | [string],
  'email' : [] | [string],
  'is_active' : [] | [boolean],
  'phone' : [] | [string],
}
export interface UpdateStudentRequest {
  'dob' : [] | [string],
  'class' : [] | [string],
  'name' : [] | [string],
  'section' : [] | [string],
  'admission_date' : [] | [string],
  'email' : [] | [string],
  'enrollment_number' : [] | [string],
  'parent_phone' : [] | [string],
  'address' : [] | [string],
  'gender' : [] | [string],
  'is_active' : [] | [boolean],
  'phone' : [] | [string],
  'monthly_fee' : [] | [bigint],
  'course' : [] | [string],
  'parent_name' : [] | [string],
}
export type UserId = string;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAdmin' : ActorMethod<[CreateAdminRequest], Admin>,
  'createClass' : ActorMethod<[CreateClassForm], ClassRecord>,
  'createNotification' : ActorMethod<[CreateNotificationRequest], Notification>,
  'createProfile' : ActorMethod<[CreateProfileRequest], Profile>,
  'createSection' : ActorMethod<[CreateSectionForm], SectionRecord>,
  'createStudent' : ActorMethod<[CreateStudentRequest], Student>,
  'deleteClass' : ActorMethod<[string], boolean>,
  'deletePayment' : ActorMethod<[string], boolean>,
  'deleteSection' : ActorMethod<[string], boolean>,
  'getAdminByProfile' : ActorMethod<[], [] | [Admin]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClassesByAdmin' : ActorMethod<[], Array<ClassRecord>>,
  'getMyProfile' : ActorMethod<[], [] | [Profile]>,
  'getNotificationsByAdmin' : ActorMethod<[], Array<Notification>>,
  'getNotificationsByStudent' : ActorMethod<[], Array<Notification>>,
  'getPaymentsByAdmin' : ActorMethod<[], Array<MonthlyPayment>>,
  'getPaymentsByStudent' : ActorMethod<[], Array<MonthlyPayment>>,
  'getSectionsByAdmin' : ActorMethod<[], Array<SectionRecord>>,
  'getSectionsByClass' : ActorMethod<[string], Array<SectionRecord>>,
  'getStudentByProfile' : ActorMethod<[], [] | [Student]>,
  'getStudentsByAdmin' : ActorMethod<[], Array<Student>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAllNotificationsRead' : ActorMethod<[], bigint>,
  'markNotificationRead' : ActorMethod<[string], boolean>,
  'recordPayment' : ActorMethod<[RecordPaymentRequest], MonthlyPayment>,
  'updateClass' : ActorMethod<[string, UpdateClassForm], [] | [ClassRecord]>,
  'updatePayment' : ActorMethod<
    [string, UpdatePaymentRequest],
    [] | [MonthlyPayment]
  >,
  'updateProfile' : ActorMethod<[UpdateProfileRequest], [] | [Profile]>,
  'updateStudent' : ActorMethod<[string, UpdateStudentRequest], [] | [Student]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];