/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UpdatePaymentRequest {
    payment_date?: Timestamp;
    payment_method?: PaymentMethod;
    amount_paid?: bigint;
    notes?: string;
}
export type Timestamp = bigint;
export interface RecordPaymentRequest {
    month: string;
    payment_date: Timestamp;
    student_id: string;
    payment_method: PaymentMethod;
    amount_paid: bigint;
    notes?: string;
}
export interface MonthlyPayment {
    id: string;
    month: string;
    payment_date: Timestamp;
    admin_id: UserId;
    student_id: string;
    created_at: Timestamp;
    payment_method: PaymentMethod;
    amount_paid: bigint;
    notes?: string;
}
export interface CreateProfileRequest {
    avatar_url?: string;
    name: string;
    role: Role;
    email: string;
    phone?: string;
}
export interface Profile {
    id: UserId;
    updated_at: Timestamp;
    avatar_url?: string;
    name: string;
    role: Role;
    created_at: Timestamp;
    email: string;
    is_active: boolean;
    phone?: string;
}
export interface CreateStudentRequest {
    joined_date: Timestamp;
    class: string;
    name: string;
    fee_start_date: Timestamp;
    email: string;
    monthly_fee: bigint;
    course: string;
}
export interface CreateAdminRequest {
    institute_code: string;
    institute_name: string;
    address?: string;
}
export type UserId = string;
export interface UpdateProfileRequest {
    avatar_url?: string;
    name?: string;
    email?: string;
    is_active?: boolean;
    phone?: string;
}
export interface CreateNotificationRequest {
    title: string;
    type: NotificationType;
    student_id?: UserId;
    message: string;
}
export interface Admin {
    id: UserId;
    created_at: Timestamp;
    institute_code: string;
    institute_name: string;
    address?: string;
    profile_id: UserId;
}
export interface Notification {
    id: string;
    is_read: boolean;
    title: string;
    admin_id: UserId;
    type: NotificationType;
    student_id?: UserId;
    created_at: Timestamp;
    message: string;
}
export interface UpdateStudentRequest {
    class?: string;
    name?: string;
    email?: string;
    is_active?: boolean;
    monthly_fee?: bigint;
    course?: string;
}
export interface Student {
    id: string;
    updated_at: Timestamp;
    joined_date: Timestamp;
    admin_id: UserId;
    class: string;
    name: string;
    fee_start_date: Timestamp;
    created_at: Timestamp;
    email: string;
    is_active: boolean;
    monthly_fee: bigint;
    course: string;
    profile_id?: UserId;
}
export enum NotificationType {
    custom = "custom",
    fee_due = "fee_due",
    overdue = "overdue",
    payment_received = "payment_received"
}
export enum PaymentMethod {
    card = "card",
    cash = "cash",
    cheque = "cheque",
    online = "online"
}
export enum Role {
    admin = "admin",
    student = "student"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAdmin(req: CreateAdminRequest): Promise<Admin>;
    createNotification(req: CreateNotificationRequest): Promise<Notification>;
    createProfile(req: CreateProfileRequest): Promise<Profile>;
    createStudent(req: CreateStudentRequest): Promise<Student>;
    deletePayment(paymentId: string): Promise<boolean>;
    getAdminByProfile(): Promise<Admin | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyProfile(): Promise<Profile | null>;
    getNotificationsByAdmin(): Promise<Array<Notification>>;
    getNotificationsByStudent(): Promise<Array<Notification>>;
    getPaymentsByAdmin(): Promise<Array<MonthlyPayment>>;
    getPaymentsByStudent(): Promise<Array<MonthlyPayment>>;
    getStudentByProfile(): Promise<Student | null>;
    getStudentsByAdmin(): Promise<Array<Student>>;
    isCallerAdmin(): Promise<boolean>;
    markAllNotificationsRead(): Promise<bigint>;
    markNotificationRead(notifId: string): Promise<boolean>;
    recordPayment(req: RecordPaymentRequest): Promise<MonthlyPayment>;
    updatePayment(paymentId: string, req: UpdatePaymentRequest): Promise<MonthlyPayment | null>;
    updateProfile(req: UpdateProfileRequest): Promise<Profile | null>;
    updateStudent(studentId: string, req: UpdateStudentRequest): Promise<Student | null>;
}
import type { Admin as _Admin, CreateAdminRequest as _CreateAdminRequest, CreateNotificationRequest as _CreateNotificationRequest, CreateProfileRequest as _CreateProfileRequest, MonthlyPayment as _MonthlyPayment, Notification as _Notification, NotificationType as _NotificationType, PaymentMethod as _PaymentMethod, Profile as _Profile, RecordPaymentRequest as _RecordPaymentRequest, Role as _Role, Student as _Student, Timestamp as _Timestamp, UpdatePaymentRequest as _UpdatePaymentRequest, UpdateProfileRequest as _UpdateProfileRequest, UpdateStudentRequest as _UpdateStudentRequest, UserId as _UserId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAdmin(arg0: CreateAdminRequest): Promise<Admin> {
        if (this.processError) {
            try {
                const result = await this.actor.createAdmin(to_candid_CreateAdminRequest_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Admin_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAdmin(to_candid_CreateAdminRequest_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Admin_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNotification(arg0: CreateNotificationRequest): Promise<Notification> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(to_candid_CreateNotificationRequest_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Notification_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(to_candid_CreateNotificationRequest_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Notification_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProfile(arg0: CreateProfileRequest): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(to_candid_CreateProfileRequest_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Profile_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(to_candid_CreateProfileRequest_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Profile_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async createStudent(arg0: CreateStudentRequest): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudent(arg0);
                return from_candid_Student_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudent(arg0);
            return from_candid_Student_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePayment(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePayment(arg0);
            return result;
        }
    }
    async getAdminByProfile(): Promise<Admin | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminByProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminByProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotificationsByAdmin(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationsByAdmin();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationsByAdmin();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotificationsByStudent(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationsByStudent();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationsByStudent();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentsByAdmin(): Promise<Array<MonthlyPayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsByAdmin();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsByAdmin();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentsByStudent(): Promise<Array<MonthlyPayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsByStudent();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsByStudent();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentByProfile(): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentByProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentByProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentsByAdmin(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsByAdmin();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsByAdmin();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAllNotificationsRead(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markNotificationRead(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async recordPayment(arg0: RecordPaymentRequest): Promise<MonthlyPayment> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPayment(to_candid_RecordPaymentRequest_n39(this._uploadFile, this._downloadFile, arg0));
                return from_candid_MonthlyPayment_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPayment(to_candid_RecordPaymentRequest_n39(this._uploadFile, this._downloadFile, arg0));
            return from_candid_MonthlyPayment_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePayment(arg0: string, arg1: UpdatePaymentRequest): Promise<MonthlyPayment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayment(arg0, to_candid_UpdatePaymentRequest_n43(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayment(arg0, to_candid_UpdatePaymentRequest_n43(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfile(arg0: UpdateProfileRequest): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(to_candid_UpdateProfileRequest_n46(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(to_candid_UpdateProfileRequest_n46(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateStudent(arg0: string, arg1: UpdateStudentRequest): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, to_candid_UpdateStudentRequest_n48(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, to_candid_UpdateStudentRequest_n48(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Admin_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Admin): Admin {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_MonthlyPayment_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MonthlyPayment): MonthlyPayment {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Admin]): Admin | null {
    return value.length === 0 ? null : from_candid_Admin_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : from_candid_Student_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MonthlyPayment]): MonthlyPayment | null {
    return value.length === 0 ? null : from_candid_MonthlyPayment_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    is_read: boolean;
    title: string;
    admin_id: _UserId;
    type: _NotificationType;
    student_id: [] | [_UserId];
    created_at: _Timestamp;
    message: string;
}): {
    id: string;
    is_read: boolean;
    title: string;
    admin_id: UserId;
    type: NotificationType;
    student_id?: UserId;
    created_at: Timestamp;
    message: string;
} {
    return {
        id: value.id,
        is_read: value.is_read,
        title: value.title,
        admin_id: value.admin_id,
        type: from_candid_NotificationType_n14(_uploadFile, _downloadFile, value.type),
        student_id: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.student_id)),
        created_at: value.created_at,
        message: value.message
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    updated_at: _Timestamp;
    avatar_url: [] | [string];
    name: string;
    role: _Role;
    created_at: _Timestamp;
    email: string;
    is_active: boolean;
    phone: [] | [string];
}): {
    id: UserId;
    updated_at: Timestamp;
    avatar_url?: string;
    name: string;
    role: Role;
    created_at: Timestamp;
    email: string;
    is_active: boolean;
    phone?: string;
} {
    return {
        id: value.id,
        updated_at: value.updated_at,
        avatar_url: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.avatar_url)),
        name: value.name,
        role: from_candid_Role_n23(_uploadFile, _downloadFile, value.role),
        created_at: value.created_at,
        email: value.email,
        is_active: value.is_active,
        phone: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    updated_at: _Timestamp;
    joined_date: _Timestamp;
    admin_id: _UserId;
    class: string;
    name: string;
    fee_start_date: _Timestamp;
    created_at: _Timestamp;
    email: string;
    is_active: boolean;
    monthly_fee: bigint;
    course: string;
    profile_id: [] | [_UserId];
}): {
    id: string;
    updated_at: Timestamp;
    joined_date: Timestamp;
    admin_id: UserId;
    class: string;
    name: string;
    fee_start_date: Timestamp;
    created_at: Timestamp;
    email: string;
    is_active: boolean;
    monthly_fee: bigint;
    course: string;
    profile_id?: UserId;
} {
    return {
        id: value.id,
        updated_at: value.updated_at,
        joined_date: value.joined_date,
        admin_id: value.admin_id,
        class: value.class,
        name: value.name,
        fee_start_date: value.fee_start_date,
        created_at: value.created_at,
        email: value.email,
        is_active: value.is_active,
        monthly_fee: value.monthly_fee,
        course: value.course,
        profile_id: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.profile_id))
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    month: string;
    payment_date: _Timestamp;
    admin_id: _UserId;
    student_id: string;
    created_at: _Timestamp;
    payment_method: _PaymentMethod;
    amount_paid: bigint;
    notes: [] | [string];
}): {
    id: string;
    month: string;
    payment_date: Timestamp;
    admin_id: UserId;
    student_id: string;
    created_at: Timestamp;
    payment_method: PaymentMethod;
    amount_paid: bigint;
    notes?: string;
} {
    return {
        id: value.id,
        month: value.month,
        payment_date: value.payment_date,
        admin_id: value.admin_id,
        student_id: value.student_id,
        created_at: value.created_at,
        payment_method: from_candid_PaymentMethod_n35(_uploadFile, _downloadFile, value.payment_method),
        amount_paid: value.amount_paid,
        notes: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    created_at: _Timestamp;
    institute_code: string;
    institute_name: string;
    address: [] | [string];
    profile_id: _UserId;
}): {
    id: UserId;
    created_at: Timestamp;
    institute_code: string;
    institute_name: string;
    address?: string;
    profile_id: UserId;
} {
    return {
        id: value.id,
        created_at: value.created_at,
        institute_code: value.institute_code,
        institute_name: value.institute_name,
        address: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.address)),
        profile_id: value.profile_id
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: null;
} | {
    fee_due: null;
} | {
    overdue: null;
} | {
    payment_received: null;
}): NotificationType {
    return "custom" in value ? NotificationType.custom : "fee_due" in value ? NotificationType.fee_due : "overdue" in value ? NotificationType.overdue : "payment_received" in value ? NotificationType.payment_received : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    student: null;
}): Role {
    return "admin" in value ? Role.admin : "student" in value ? Role.student : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    card: null;
} | {
    cash: null;
} | {
    cheque: null;
} | {
    online: null;
}): PaymentMethod {
    return "card" in value ? PaymentMethod.card : "cash" in value ? PaymentMethod.cash : "cheque" in value ? PaymentMethod.cheque : "online" in value ? PaymentMethod.online : value;
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MonthlyPayment>): Array<MonthlyPayment> {
    return value.map((x)=>from_candid_MonthlyPayment_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Array<Student> {
    return value.map((x)=>from_candid_Student_n25(_uploadFile, _downloadFile, x));
}
function to_candid_CreateAdminRequest_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateAdminRequest): _CreateAdminRequest {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CreateNotificationRequest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateNotificationRequest): _CreateNotificationRequest {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_CreateProfileRequest_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateProfileRequest): _CreateProfileRequest {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_NotificationType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): _NotificationType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_RecordPaymentRequest_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecordPaymentRequest): _RecordPaymentRequest {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UpdatePaymentRequest_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdatePaymentRequest): _UpdatePaymentRequest {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProfileRequest_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProfileRequest): _UpdateProfileRequest {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateStudentRequest_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateStudentRequest): _UpdateStudentRequest {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    avatar_url?: string;
    name: string;
    role: Role;
    email: string;
    phone?: string;
}): {
    avatar_url: [] | [string];
    name: string;
    role: _Role;
    email: string;
    phone: [] | [string];
} {
    return {
        avatar_url: value.avatar_url ? candid_some(value.avatar_url) : candid_none(),
        name: value.name,
        role: to_candid_Role_n19(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    institute_code: string;
    institute_name: string;
    address?: string;
}): {
    institute_code: string;
    institute_name: string;
    address: [] | [string];
} {
    return {
        institute_code: value.institute_code,
        institute_name: value.institute_name,
        address: value.address ? candid_some(value.address) : candid_none()
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    month: string;
    payment_date: Timestamp;
    student_id: string;
    payment_method: PaymentMethod;
    amount_paid: bigint;
    notes?: string;
}): {
    month: string;
    payment_date: _Timestamp;
    student_id: string;
    payment_method: _PaymentMethod;
    amount_paid: bigint;
    notes: [] | [string];
} {
    return {
        month: value.month,
        payment_date: value.payment_date,
        student_id: value.student_id,
        payment_method: to_candid_PaymentMethod_n41(_uploadFile, _downloadFile, value.payment_method),
        amount_paid: value.amount_paid,
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    payment_date?: Timestamp;
    payment_method?: PaymentMethod;
    amount_paid?: bigint;
    notes?: string;
}): {
    payment_date: [] | [_Timestamp];
    payment_method: [] | [_PaymentMethod];
    amount_paid: [] | [bigint];
    notes: [] | [string];
} {
    return {
        payment_date: value.payment_date ? candid_some(value.payment_date) : candid_none(),
        payment_method: value.payment_method ? candid_some(to_candid_PaymentMethod_n41(_uploadFile, _downloadFile, value.payment_method)) : candid_none(),
        amount_paid: value.amount_paid ? candid_some(value.amount_paid) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    avatar_url?: string;
    name?: string;
    email?: string;
    is_active?: boolean;
    phone?: string;
}): {
    avatar_url: [] | [string];
    name: [] | [string];
    email: [] | [string];
    is_active: [] | [boolean];
    phone: [] | [string];
} {
    return {
        avatar_url: value.avatar_url ? candid_some(value.avatar_url) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        is_active: value.is_active ? candid_some(value.is_active) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    class?: string;
    name?: string;
    email?: string;
    is_active?: boolean;
    monthly_fee?: bigint;
    course?: string;
}): {
    class: [] | [string];
    name: [] | [string];
    email: [] | [string];
    is_active: [] | [boolean];
    monthly_fee: [] | [bigint];
    course: [] | [string];
} {
    return {
        class: value.class ? candid_some(value.class) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        is_active: value.is_active ? candid_some(value.is_active) : candid_none(),
        monthly_fee: value.monthly_fee ? candid_some(value.monthly_fee) : candid_none(),
        course: value.course ? candid_some(value.course) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    type: NotificationType;
    student_id?: UserId;
    message: string;
}): {
    title: string;
    type: _NotificationType;
    student_id: [] | [_UserId];
    message: string;
} {
    return {
        title: value.title,
        type: to_candid_NotificationType_n10(_uploadFile, _downloadFile, value.type),
        student_id: value.student_id ? candid_some(value.student_id) : candid_none(),
        message: value.message
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): {
    custom: null;
} | {
    fee_due: null;
} | {
    overdue: null;
} | {
    payment_received: null;
} {
    return value == NotificationType.custom ? {
        custom: null
    } : value == NotificationType.fee_due ? {
        fee_due: null
    } : value == NotificationType.overdue ? {
        overdue: null
    } : value == NotificationType.payment_received ? {
        payment_received: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    student: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.student ? {
        student: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    card: null;
} | {
    cash: null;
} | {
    cheque: null;
} | {
    online: null;
} {
    return value == PaymentMethod.card ? {
        card: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value == PaymentMethod.cheque ? {
        cheque: null
    } : value == PaymentMethod.online ? {
        online: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
